version: '3.8'
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
    networks:
      - internal

  web:
    image: nginx:1.27.3
    restart: always
    networks:
      - internal
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - db
    depends_on:
      - db

  frontend:
    build: ./services/frontend
    restart: always
    networks:
      - internal
    ports:
      - "80:80"
    volumes:
      - ./nginx/frontend-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

networks:
  internal:
    driver: bridge
